version: '3.8'

services:
  simple_server:
    build:
      context: ./simple_server
      dockerfile: Dockerfile
    networks:
      - default

  nginx:
    image: nginx:1.23.4
    ports:
    - "80:8080"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - default

networks:
  default: